<?php

declare(strict_types=1);

namespace App\Support\System;

/**
 * FrontendUrlBuilder
 * 
 * Centralized utility for generating frontend URLs.
 * Ensures consistent base URL usage and query parameter formatting.
 */
class FrontendUrlBuilder
{
    /**
     * Build a full frontend URL.
     *
     * @param string $path The frontend path (e.g., '/dashboard' or 'reset-password')
     * @param array $query Optional query parameters
     * @return string
     */
    public static function build(string $path, array $query = []): string
    {
        $baseUrl = config('app.frontend_url', 'http://localhost:3000');
        $url = rtrim($baseUrl, '/') . '/' . ltrim($path, '/');
        
        if (!empty($query)) {
            $url .= '?' . http_build_query($query);
        }
        
        return $url;
    }

    /**
     * Build a frontend URL with signed query parameters from a backend route.
     * Useful for email verification and password reset links.
     *
     * @param string $path The frontend path
     * @param string $backendSignedUrl The signed URL generated by URL::temporarySignedRoute()
     * @return string
     */
    public static function buildSigned(string $path, string $backendSignedUrl): string
    {
        $query = parse_url($backendSignedUrl, PHP_URL_QUERY);
        $url = self::build($path);
        
        return $url . ($query ? '?' . $query : '');
    }
}
