<?php

declare(strict_types=1);

namespace App\Support\System;

use Illuminate\Http\Request;

/**
 * FrontendUrlBuilder
 * 
 * Centralized utility for generating frontend URLs.
 * Ensures consistent base URL usage and query parameter formatting.
 */
class FrontendUrlBuilder
{
    private const SOCIAL_AUTH_FRONTEND_URL_SESSION_KEY = 'auth.social.frontend_url';

    /**
     * Build a full frontend URL.
     *
     * @param string $path The frontend path (e.g., '/dashboard' or 'reset-password')
     * @param array $query Optional query parameters
     * @param string|null $baseUrl Optional frontend base URL override
     * @return string
     */
    public static function build(string $path, array $query = [], ?string $baseUrl = null): string
    {
        $resolvedBaseUrl = self::normalizeBaseUrl($baseUrl);
        $url = $resolvedBaseUrl . '/' . ltrim($path, '/');
        
        if (!empty($query)) {
            $url .= '?' . http_build_query($query);
        }
        
        return $url;
    }

    /**
     * Build a frontend URL with signed query parameters from a backend route.
     * Useful for email verification and password reset links.
     *
     * @param string $path The frontend path
     * @param string $backendSignedUrl The signed URL generated by URL::temporarySignedRoute()
     * @return string
     */
    public static function buildSigned(string $path, string $backendSignedUrl, ?string $baseUrl = null): string
    {
        $query = parse_url($backendSignedUrl, PHP_URL_QUERY);
        $url = self::build($path, baseUrl: $baseUrl);
        
        return $url . ($query ? '?' . $query : '');
    }

    /**
     * Remember the originating storefront base URL for the social-auth flow.
     */
    public static function rememberSocialAuthFrontendUrl(Request $request): ?string
    {
        $frontendUrl = self::resolveRequestFrontendUrl($request);

        if ($frontendUrl !== null && $request->hasSession()) {
            $request->session()->put(self::SOCIAL_AUTH_FRONTEND_URL_SESSION_KEY, $frontendUrl);
        }

        return $frontendUrl;
    }

    /**
     * Pull the previously remembered storefront base URL for the social-auth flow.
     */
    public static function pullSocialAuthFrontendUrl(Request $request): ?string
    {
        if (!$request->hasSession()) {
            return null;
        }

        $frontendUrl = $request->session()->pull(self::SOCIAL_AUTH_FRONTEND_URL_SESSION_KEY);

        return is_string($frontendUrl) ? self::normalizeAbsoluteUrl($frontendUrl) : null;
    }

    /**
     * Resolve a storefront base URL from request headers.
     *
     * Priority:
     * 1. X-Frontend-Url custom header (explicitly set by frontend)
     * 2. Origin header
     * 3. Referer header
     * 4. Construct from Host header (used by Nuxt storefront which forwards the original host)
     */
    public static function resolveRequestFrontendUrl(Request $request): ?string
    {
        $candidates = [
            $request->headers->get('x-frontend-url'),
            $request->headers->get('origin'),
            $request->headers->get('referer'),
        ];

        foreach ($candidates as $candidate) {
            $normalized = self::normalizeAbsoluteUrl($candidate);

            if ($normalized !== null && !self::isExternalOAuthProvider($normalized)) {
                return $normalized;
            }
        }

        // Fall back to constructing from the Host header (for proxies that forward it)
        $host = $request->getHost();
        if ($host && $host !== 'localhost' && !filter_var($host, FILTER_VALIDATE_IP)) {
            $scheme = $request->getScheme() ?: 'http';
            $port = $request->getPort();
            $constructed = sprintf('%s://%s%s', $scheme, $host, $port !== 80 && $port !== 443 ? ':' . $port : '');
            $normalized = self::normalizeAbsoluteUrl($constructed);

            if ($normalized !== null && !self::isExternalOAuthProvider($normalized)) {
                return $normalized;
            }
        }

        return null;
    }

    /**
     * Build a frontend URL from a store domain.
     *
     * Uses the configured frontend URL's scheme and port as a template,
     * replacing the host with the given domain.
     */
    public static function fromStoreDomain(string $domain): string
    {
        $defaultUrl = config('app.frontend_url', 'http://localhost:3000');
        $scheme = parse_url($defaultUrl, PHP_URL_SCHEME) ?: 'http';
        $port = parse_url($defaultUrl, PHP_URL_PORT);

        return sprintf('%s://%s%s', $scheme, $domain, $port !== null ? ':' . $port : '');
    }

    /**
     * Check if a URL belongs to an external OAuth provider — these must never
     * be treated as the storefront's base URL for redirects.
     */
    private static function isExternalOAuthProvider(string $url): bool
    {
        $host = parse_url($url, PHP_URL_HOST);

        if (!is_string($host)) {
            return false;
        }

        // Exclude Google OAuth domains
        if ($host === 'accounts.google.com' || $host === 'google.com') {
            return true;
        }

        return false;
    }

    private static function normalizeBaseUrl(?string $baseUrl): string
    {
        return self::normalizeAbsoluteUrl($baseUrl)
            ?? self::normalizeAbsoluteUrl((string) config('app.frontend_url', 'http://localhost:3000'))
            ?? 'http://localhost:3000';
    }

    private static function normalizeAbsoluteUrl(?string $url): ?string
    {
        if (!is_string($url) || trim($url) === '') {
            return null;
        }

        $trimmed = trim($url);
        if (filter_var($trimmed, FILTER_VALIDATE_URL) === false) {
            return null;
        }

        $scheme = parse_url($trimmed, PHP_URL_SCHEME);
        $host = parse_url($trimmed, PHP_URL_HOST);
        $port = parse_url($trimmed, PHP_URL_PORT);

        if (!is_string($scheme) || !in_array($scheme, ['http', 'https'], true) || !is_string($host) || $host === '') {
            return null;
        }

        return sprintf('%s://%s%s', $scheme, $host, $port !== null ? ':' . $port : '');
    }
}
